### PR TITLE
0.7.9+mobile

### PR DESCRIPTION
**Pull request by bitspittle**
Hey Deepanshu,

If you're busy, let me know, and I can just submit this. However, some pretty big changes going on here, so I thought I'd give you a chance to look before submitting.

It is probably worth pulling down these two commits and running our site in mobile mode (you can do this by following these instructions: https://developer.chrome.com/docs/devtools/device-mode/). I tweaked a bunch of sizes, but some things still feel a little off. I also hide the hero sample and CLI sections in mobile mode because I couldn't get them to look good, but you might have more luck!

### CODE REVIEW

**Comment by deepanshu11madan** [comment]
Looks good on mobile, the text is more readable for sure and no hero image on mobile is ok for now. 

One thing though, looks like the border/shadow is broken in all places like the Nav header bottom, Feature items, and CTA section unless it was intentional?

**Comment by bitspittle** [comment]
Definitely not intentional, especially shadows! I thought the border was removed from the CTA section before I started making changes to it? It's actually a bit easier that way because in mobile mode it's all rendered in a single column instead of three. I'm not sure what we'd want it to look like in that case.

I'll try to check the site w/o my changes and compare it to after them. Maybe the issue wasn't due to these changes directly but perhaps something I broke in Kobweb 0.7.9

**Comment by deepanshu11madan** [comment]
if it helps, looks like com.varabyte.kobweb.compose.ui.modifiers.boxShadow layout modifier works correctly, it's the custom boxShadow modifier in BoxShadow.kt which might be broken, probably after this [refactor](https://github.com/varabyte/kobweb-site/commit/97ac19227d83445705fef766e6e207100d406697#diff-a1d7ed9ca3d58c2cd1d5f605d663cbccec13baf938fc9fd471b31fbe2a276f90)

**Comment by bitspittle** [comment]
Oh you're right! I see what I did. Will apply a fix in a commit shortly.

**Comment by bitspittle** [comment]
OK, added a third commit to the chain. Feel free to pull down and take a look.

Thanks for investigating!

**Comment by deepanshu11madan** [comment]
it works! going to merge this.

**Pull request merged**
